# Starter pipeline

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Pay-As-You-Go(2de30eb6-ccf1-4f0e-95e3-888d38bce35a)'
    azureContainerRegistry: '{"loginServer":"registryzero1.azurecr.io", "id" : "/subscriptions/2de30eb6-ccf1-4f0e-95e3-888d38bce35a/resourceGroups/Microservices-Demo/providers/Microsoft.ContainerRegistry/registries/registryzero1"}'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'docker compose run'