version: '3.4'

services:
  photoengine-frontend:
    image: photoenginefrontend
    environment:
        - gatewayapiurl=http://apigatewayengine
    build:
      context: https://github.com/iamacodrr/AzureMicroservices-Demo/tree/master/PhotoEngine-FrontEnd
      dockerfile: Dockerfile
    depends_on:
        - api-gatewayengine
    ports:
    - "5100:80"
  api-gatewayengine:
    image: apigatewayengine
    environment:
        - peapiurl=http://photoengineapi
    build:
      context: https://github.com/iamacodrr/AzureMicroservices-Demo/tree/master/API-GatewayEngine
      dockerfile: Dockerfile
    depends_on:
        - photoengiine-api
    ports:
    - "5100:80"
  photoengiine-api:
    image: photoengineapi
    build:
        context: https://github.com/iamacodrr/AzureMicroservices-Demo/tree/master/PhotoEngine-API
        dockerfile: Dockerfile
    expose:
      - "80"
    ports:
      - "5101:80"