version: '3.4'

services:
  photoengine-frontend:
    image: photoenginefrontend
    environment:
        - gatewayapiurl=http://apigatewayengine
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
        - api-gatewayengine
    ports:
    - "5100:80"
  api-gatewayengine:
    image: apigatewayengine
    environment:
        - peapiurl=http://photoengineapi
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
        - photoengiine-api
    ports:
    - "5100:80"
  photoengiine-api:
    image: photoengineapi
    build:
        context: .
        dockerfile: Dockerfile
    expose:
      - "80"
    ports:
      - "5101:80"