version: '3.4'

services:
  photoengiine-api:
    image: photoengineapi
    build:
        context: .
        dockerfile: PhotoEngine-API/Dockerfile
    expose:
      - "80"
    ports:
      - "5101:80"